# Generated by Django 4.2.2 on 2023-07-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
